### ISSUE TITLE
When compiling cannot find header file.

### ISSUE THREAD

**Issue by paulfecht** [outofambit/easy-neopixels#3]
Hello,  I'm excited to use this library but even though I have the header installed it will not compile.  I've tried duplicating the header file, stopping and restarting the Arduino IDE to no avail.  This seems to be a common issue.  I was able to resolve it with other libraries but this seems persistent.

blink:5:27: error: EasyNeopixels.h: No such file or directory
compilation terminated.
exit status 1
EasyNeopixels.h: No such file or directory

**Comment by erikLundstedt** [comment]
try using EasyNeoPixels.h instead of EasyNeopixels.h
i think its a miss in the examples

**Comment by outofambit** [comment]
hi @paulfecht! i'm so sorry i missed this issue come through! did the fix @erikLundstedt mentioned work for you?

i'm going to fix that in both included examples and release an update of the library tomorrow.

**Comment by outofambit** [comment]
@paulfecht I've merged this fix and released a new version of the library. Please Let me know if you have any more issues! Thanks!!
