### ISSUE TITLE
RGB?

### ISSUE THREAD

**Issue by ANSB** [outofambit/easy-neopixels#8]
If the function writeEasyNeoPixel needs "num of the pixel, RED value, GREEN value, BLUE value" as in the colorSequence example, this mean the comment on main page in front of 
writeEasyNeoPixel(0, 255, 255, 0);  is wong as 255,255,0 = yellow and not purple.
Regards

**Comment by outofambit** [comment]
hi @ANSB! oh wow you are correct, i've looked past that for years now. if you want to make a PR to fix that I'd be happy to review + merge, otherwise I can fix this later. thanks for pointing this out!

**Comment by erikLundstedt** [comment]
POKE @outofambit
